apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: eventstrat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: your-dockerhub-username/analytics:latest
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: eventstrat
spec:
  selector:
    app: analytics
  ports:
    - port: 80
      targetPort: 3003
