apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting
  namespace: eventstrat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      labels:
        app: meeting
    spec:
      containers:
        - name: meeting
          image: your-dockerhub-username/meeting:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: meeting
  namespace: eventstrat
spec:
  selector:
    app: meeting
  ports:
    - port: 80
      targetPort: 3002
